import type { Metadata } from "next";
import "./globals.css";
import { Avatar, Badge, Dropdown, Flex } from "antd";
import {
  BellOutlined,
  DownOutlined,
  SettingOutlined,
  UserOutlined,
} from "@ant-design/icons";

import Image from "next/image";
import { NAVDATA } from "@/lib/constants";
import type { MenuProps } from "antd";

export const metadata: Metadata = {
  title: "Engaz",
  description: "Generated by create next app",
};
const items: MenuProps["items"] = [
  { key: "1", label: "My Account" },
  { key: "2", label: "Profile" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const selectedTabStyle = "text-white border-white bg-slate-500";
  return (
    <html lang="en">
      <body className="bg-white">
        <Flex className="">
          {/* Left section -------------------------------------------------------------------------------------------------- */}
          <Flex
            vertical
            gap="middle"
            className="bg-customBlue px-12 py-8 rounded-br-3xl border-r-2 fixed left-0 top-0 h-screen"
          >
            <Image
              src="/engaz.png"
              alt="Next.js logo"
              width={180}
              height={38}
              priority
              className="mb-10"
            />
            {NAVDATA.map((navItem, i) => (
              <Flex
                gap="middle"
                key={navItem.text}
                className={`border-l-4 p-3 rounded-r-2xl text-gray-400 border-customBlue  hover:text-white hover:border-white hover:bg-slate-500 hover:cursor-pointer ${
                  i === 1 ? selectedTabStyle : ""
                }`}
              >
                {navItem.icon}
                <p className=" w-40 text-lg ">{navItem.text}</p>
              </Flex>
            ))}
          </Flex>

          <p className="px-36 w-80"></p>

          <Flex vertical className=" w-screen h-screen ">
            {/* Navigation Bar--------------------------------------------------------------------------------------------------*/}
            <Flex
              justify="end"
              gap="large"
              className="bg-customBlue pt-6 pb-8 px-16 rounded-br-3xl"
            >
              <SettingOutlined className="text-2xl" />
              <Badge dot className="text-3xl text-white  mt-3">
                <BellOutlined />
              </Badge>
              <Dropdown menu={{ items }}>
                <div>
                  <Avatar size={60} icon={<UserOutlined />} />
                  <DownOutlined className="ml-2" />
                </div>
              </Dropdown>
            </Flex>
            {/* Content --------------------------------------------------------------------------------------------------*/}
            <Flex vertical className=" p-10 ">
              {children}
            </Flex>
          </Flex>
        </Flex>
      </body>
    </html>
  );
}
